### ISSUE TITLE
Initial account isn't removed immediately

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-ios#107]
**Bug Description**
After a failed identity, the initial account wasn’t removed immediately. It wasn’t removed before I browsed away from the page and back again. This happened at the same time as Notabene started returning new error messages, but I can’t tell if it’s related.

The error isn't persistently reproducible, so further investigation is probably required.

**Steps to Reproduce**
It doesn't necessarily work:
- Try to force a failed identity
- Wait on the Accounts page, and see what happens.
- If the failed accounts stays and has a red exclamation mark on it, it worked.

**Expected Result**
- Initial accounts of failed identities are always removed immediately.

**Actual Result**
- One time the initial account wasn't removed immediately.

**Versions**
- Software Version: 1.0(22)
- OS: iOS
- Browser
- Mobile device, if applicable

**Comment by concordium-cl** [comment]
I can reproduce this quite consistently when following @jens-concordium's steps to reproduce. When I then click on the failed account, the app crashes. I therefore add the issue to the project board to be retested when @td202's fix is merged.

**Comment by jens-concordium** [comment]
@concordium-cl, @kristiyandobrev, @ruxandra-constantinescu

This is still a problem in 1.0(25), but I guess it's probably related to the issue Thomas also mentioned, @ruxandra-constantinescu?

**Comment by concordium-cl** [comment]
Seems to work in v1.0.26.
